/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bhlrmDraco.gltf 
*/
"use client";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/bhlrmDraco.gltf");
	const { actions } = useAnimations(animations, group);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<primitive object={nodes.mixamorigHips} />
					<skinnedMesh
						name="pilot_medium_bloodhound_LOD0_SEModelMesh039"
						geometry={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh039.geometry
						}
						material={materials["Material.008"]}
						skeleton={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh039.skeleton
						}
					/>
					<skinnedMesh
						name="pilot_medium_bloodhound_LOD0_SEModelMesh040"
						geometry={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh040.geometry
						}
						material={materials["Material.007"]}
						skeleton={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh040.skeleton
						}
					/>
					<skinnedMesh
						name="pilot_medium_bloodhound_LOD0_SEModelMesh041"
						geometry={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh041.geometry
						}
						material={materials["Material.006"]}
						skeleton={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh041.skeleton
						}
					/>
					<skinnedMesh
						name="pilot_medium_bloodhound_LOD0_SEModelMesh042"
						geometry={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh042.geometry
						}
						material={materials["Material.004"]}
						skeleton={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh042.skeleton
						}
					/>
					<skinnedMesh
						name="pilot_medium_bloodhound_LOD0_SEModelMesh043"
						geometry={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh043.geometry
						}
						material={materials["Material.005"]}
						skeleton={
							nodes.pilot_medium_bloodhound_LOD0_SEModelMesh043.skeleton
						}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/bhlrmDraco.gltf");
