/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bloodhound.gltf 
*/
"use client";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/bloodhound.gltf");
	const { actions } = useAnimations(animations, group);
	useEffect(() => {
		actions.sitting.play();
	});
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<primitive object={nodes.mixamorigHips} />
					<skinnedMesh
						name="body"
						geometry={nodes.body.geometry}
						material={materials.bloodhound_base_body}
						skeleton={nodes.body.skeleton}
					/>
					<skinnedMesh
						name="fur"
						geometry={nodes.fur.geometry}
						material={materials.bloodhound_base_fur}
						skeleton={nodes.fur.skeleton}
					/>
					<skinnedMesh
						name="gauntlets"
						geometry={nodes.gauntlets.geometry}
						material={materials.bloodhound_base_gauntlet}
						skeleton={nodes.gauntlets.skeleton}
					/>
					<skinnedMesh
						name="gear"
						geometry={nodes.gear.geometry}
						material={materials["bloodhound_base_gear.002"]}
						skeleton={nodes.gear.skeleton}
					/>
					<skinnedMesh
						name="head"
						geometry={nodes.head.geometry}
						material={materials.bloodhound_base_head}
						skeleton={nodes.head.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/bloodhound.gltf");
