/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 horizon.gltf 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/horizon.gltf");
	const { actions } = useAnimations(animations, group);
	useEffect(() => {
		actions.sitting.play();
	});
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<primitive object={nodes.mixamorigHips} />
					<skinnedMesh
						name="body"
						geometry={nodes.body.geometry}
						material={materials.horizon_base_body}
						skeleton={nodes.body.skeleton}
					/>
					<skinnedMesh
						name="face"
						geometry={nodes.face.geometry}
						material={materials.horizon_base_head}
						skeleton={nodes.face.skeleton}
					/>
					<skinnedMesh
						name="gear"
						geometry={nodes.gear.geometry}
						material={materials.horizon_base_gear}
						skeleton={nodes.gear.skeleton}
					/>
					<skinnedMesh
						name="hair"
						geometry={nodes.hair.geometry}
						material={materials.horizon_base_hair}
						skeleton={nodes.hair.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/horizon.gltf");
